<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-REJ3M5T" failures="1" tests="8" name="com.dennismamyala.automation.My_First_Project.ErrorValidationTest" time="233.736" errors="0" timestamp="2025-09-02T11:57:46 SAST" skipped="2">
  <testcase classname="com.dennismamyala.automation.My_First_Project.ErrorValidationTest" name="loginErrorValidation" time="34.934">
    <failure message="expected [ogin failed! Please ensure the username and password are valid.] but found [Login failed! Please ensure the username and password are valid.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [ogin failed! Please ensure the username and password are valid.] but found [Login failed! Please ensure the username and password are valid.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:644)
at Utils.WebDriverUtils.assertEquals(WebDriverUtils.java:46)
at com.dennismamyala.automation.My_First_Project.Pages.Login_Page.hasErrorAppeared(Login_Page.java:63)
at com.dennismamyala.automation.My_First_Project.Base.BaseTest.hasErrorMessageAppeared(BaseTest.java:122)
at com.dennismamyala.automation.My_First_Project.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="com.dennismamyala.automation.My_First_Project.ErrorValidationTest" name="loginErrorValidation" time="25.238"/>
  <testcase classname="com.dennismamyala.automation.My_First_Project.ErrorValidationTest" name="bookingErrorValidation" time="28.410"/>
  <testcase classname="com.dennismamyala.automation.My_First_Project.ErrorValidationTest" name="loginErrorValidation" time="27.842">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="com.dennismamyala.automation.My_First_Project.ErrorValidationTest" name="loginErrorValidation" time="28.533"/>
  <testcase classname="com.dennismamyala.automation.My_First_Project.ErrorValidationTest" name="loginErrorValidation" time="29.068"/>
  <testcase classname="com.dennismamyala.automation.My_First_Project.ErrorValidationTest" name="loginErrorValidation" time="25.993">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="com.dennismamyala.automation.My_First_Project.ErrorValidationTest" name="bookingErrorValidation" time="33.718"/>
</testsuite> <!-- com.dennismamyala.automation.My_First_Project.ErrorValidationTest -->
